// <auto-generated />
using System;
using AvgApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AvgApi.Migrations
{
    [DbContext(typeof(AvgContext))]
    [Migration("20220524151845_inicial1")]
    partial class inicial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AvgApi.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAgora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aluno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "06348303179",
                            DataAgora = new DateTime(2022, 5, 24, 12, 18, 43, 458, DateTimeKind.Local).AddTicks(2700),
                            DataExclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(5045),
                            Nome = "Pedro Henrique",
                            Sobrenome = "José"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "454321321",
                            DataAgora = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6616),
                            DataExclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6623),
                            Nome = "João Pereira",
                            Sobrenome = "Antonia"
                        },
                        new
                        {
                            Id = 4,
                            Cpf = "4542123113",
                            DataAgora = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6626),
                            DataExclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6627),
                            Nome = "Raimunda",
                            Sobrenome = "Rafael"
                        },
                        new
                        {
                            Id = 5,
                            Cpf = "789456231",
                            DataAgora = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6628),
                            DataExclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6630),
                            Nome = "Ronaldo",
                            Sobrenome = "Pinto"
                        },
                        new
                        {
                            Id = 7,
                            Cpf = "4562313",
                            DataAgora = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6631),
                            DataExclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6633),
                            Nome = "Cleuso",
                            Sobrenome = "Reinaldo"
                        },
                        new
                        {
                            Id = 8,
                            Cpf = "06348303179",
                            DataAgora = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6634),
                            DataExclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2022, 5, 24, 12, 18, 43, 459, DateTimeKind.Local).AddTicks(6635),
                            Nome = "Paulo",
                            Sobrenome = "José"
                        });
                });

            modelBuilder.Entity("AvgApi.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunoDisciplina");

                    b.HasData(
                        new
                        {
                            Id = 30,
                            AlunoId = 1,
                            DisciplinaId = 1
                        },
                        new
                        {
                            Id = 31,
                            AlunoId = 1,
                            DisciplinaId = 2
                        },
                        new
                        {
                            Id = 32,
                            AlunoId = 1,
                            DisciplinaId = 3
                        },
                        new
                        {
                            Id = 33,
                            AlunoId = 1,
                            DisciplinaId = 4
                        },
                        new
                        {
                            Id = 34,
                            AlunoId = 1,
                            DisciplinaId = 5
                        },
                        new
                        {
                            Id = 35,
                            AlunoId = 2,
                            DisciplinaId = 4
                        },
                        new
                        {
                            Id = 36,
                            AlunoId = 2,
                            DisciplinaId = 3
                        },
                        new
                        {
                            Id = 37,
                            AlunoId = 2,
                            DisciplinaId = 2
                        },
                        new
                        {
                            Id = 38,
                            AlunoId = 7,
                            DisciplinaId = 4
                        },
                        new
                        {
                            Id = 39,
                            AlunoId = 7,
                            DisciplinaId = 3
                        },
                        new
                        {
                            Id = 40,
                            AlunoId = 7,
                            DisciplinaId = 2
                        },
                        new
                        {
                            Id = 41,
                            AlunoId = 7,
                            DisciplinaId = 1
                        },
                        new
                        {
                            Id = 42,
                            AlunoId = 4,
                            DisciplinaId = 1
                        },
                        new
                        {
                            Id = 43,
                            AlunoId = 4,
                            DisciplinaId = 4
                        },
                        new
                        {
                            Id = 44,
                            AlunoId = 4,
                            DisciplinaId = 3
                        },
                        new
                        {
                            Id = 45,
                            AlunoId = 5,
                            DisciplinaId = 5
                        },
                        new
                        {
                            Id = 46,
                            AlunoId = 5,
                            DisciplinaId = 4
                        },
                        new
                        {
                            Id = 47,
                            AlunoId = 5,
                            DisciplinaId = 3
                        },
                        new
                        {
                            Id = 48,
                            AlunoId = 5,
                            DisciplinaId = 2
                        },
                        new
                        {
                            Id = 49,
                            AlunoId = 5,
                            DisciplinaId = 1
                        },
                        new
                        {
                            Id = 50,
                            AlunoId = 7,
                            DisciplinaId = 1
                        },
                        new
                        {
                            Id = 51,
                            AlunoId = 7,
                            DisciplinaId = 2
                        },
                        new
                        {
                            Id = 52,
                            AlunoId = 7,
                            DisciplinaId = 3
                        },
                        new
                        {
                            Id = 53,
                            AlunoId = 7,
                            DisciplinaId = 4
                        },
                        new
                        {
                            Id = 54,
                            AlunoId = 7,
                            DisciplinaId = 5
                        });
                });

            modelBuilder.Entity("AvgApi.Models.CategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("AvgApi.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoExtra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDespesaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoDespesaId");

                    b.ToTable("Despesa");
                });

            modelBuilder.Entity("AvgApi.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplina");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("AvgApi.Models.Investimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoInvestimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cotas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInvestimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoExtra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DividendosAcoes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DividenteYield")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoInvestimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoInvestimentoId");

                    b.ToTable("Investimento");
                });

            modelBuilder.Entity("AvgApi.Models.PessoaFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PessoaFisica");
                });

            modelBuilder.Entity("AvgApi.Models.PessoaJuridica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InscEstadualIsenta")
                        .HasColumnType("bit");

                    b.Property<bool>("InscMunicipalIsenta")
                        .HasColumnType("bit");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PessoaJuridica");
                });

            modelBuilder.Entity("AvgApi.Models.ProdutoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaModelId")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DscProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("InfoProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoriaProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolegadaProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeProduto")
                        .HasColumnType("int");

                    b.Property<string>("TamanhoProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorUniProduto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoltagemProduto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaModelId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("AvgApi.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Lauro"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Roberto"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ronaldo"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Alexandre"
                        });
                });

            modelBuilder.Entity("AvgApi.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoExtra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontePagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoReceitaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorMedia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoReceitaId");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("AvgApi.Models.ResumoReceitaDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DespesaId")
                        .HasColumnType("int");

                    b.Property<int>("InvestimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PorcentagemDespesa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PorcentagemInvestimento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PorcentagemReceita")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PorcentagemTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorMedia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DespesaId");

                    b.HasIndex("InvestimentoId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ResumoReceitaDespesa");
                });

            modelBuilder.Entity("AvgApi.Models.TipoDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoDespesa");
                });

            modelBuilder.Entity("AvgApi.Models.TipoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoIvestimento");
                });

            modelBuilder.Entity("AvgApi.Models.TipoReceita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoReceita");
                });

            modelBuilder.Entity("AvgApi.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("AvgApi.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvgApi.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("AvgApi.Models.Despesa", b =>
                {
                    b.HasOne("AvgApi.Models.TipoDespesa", "TipoDespesa")
                        .WithMany("Despesas")
                        .HasForeignKey("TipoDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDespesa");
                });

            modelBuilder.Entity("AvgApi.Models.Disciplina", b =>
                {
                    b.HasOne("AvgApi.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("AvgApi.Models.Investimento", b =>
                {
                    b.HasOne("AvgApi.Models.TipoInvestimento", "TipoInvestimento")
                        .WithMany("Investimentos")
                        .HasForeignKey("TipoInvestimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoInvestimento");
                });

            modelBuilder.Entity("AvgApi.Models.ProdutoModel", b =>
                {
                    b.HasOne("AvgApi.Models.CategoriaModel", "CategoriaModels")
                        .WithMany("ProdutoModels")
                        .HasForeignKey("CategoriaModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaModels");
                });

            modelBuilder.Entity("AvgApi.Models.Receita", b =>
                {
                    b.HasOne("AvgApi.Models.TipoReceita", "TipoReceita")
                        .WithMany("Receitas")
                        .HasForeignKey("TipoReceitaId");

                    b.Navigation("TipoReceita");
                });

            modelBuilder.Entity("AvgApi.Models.ResumoReceitaDespesa", b =>
                {
                    b.HasOne("AvgApi.Models.Despesa", "Despesa")
                        .WithMany("ResumoReceitaDespesas")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvgApi.Models.Investimento", "Investimento")
                        .WithMany("ResumoReceitaDespesas")
                        .HasForeignKey("InvestimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvgApi.Models.Receita", "Receita")
                        .WithMany("ResumoReceitaDespesas")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despesa");

                    b.Navigation("Investimento");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("AvgApi.Models.Aluno", b =>
                {
                    b.Navigation("AlunosDisciplinas");
                });

            modelBuilder.Entity("AvgApi.Models.CategoriaModel", b =>
                {
                    b.Navigation("ProdutoModels");
                });

            modelBuilder.Entity("AvgApi.Models.Despesa", b =>
                {
                    b.Navigation("ResumoReceitaDespesas");
                });

            modelBuilder.Entity("AvgApi.Models.Disciplina", b =>
                {
                    b.Navigation("AlunosDisciplinas");
                });

            modelBuilder.Entity("AvgApi.Models.Investimento", b =>
                {
                    b.Navigation("ResumoReceitaDespesas");
                });

            modelBuilder.Entity("AvgApi.Models.Professor", b =>
                {
                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("AvgApi.Models.Receita", b =>
                {
                    b.Navigation("ResumoReceitaDespesas");
                });

            modelBuilder.Entity("AvgApi.Models.TipoDespesa", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("AvgApi.Models.TipoInvestimento", b =>
                {
                    b.Navigation("Investimentos");
                });

            modelBuilder.Entity("AvgApi.Models.TipoReceita", b =>
                {
                    b.Navigation("Receitas");
                });
#pragma warning restore 612, 618
        }
    }
}
